server:
  port: 8082

#含义
#网关端口是 8082
#匹配请求路径 /api/** 的请求
#去掉第 1 个路径前缀（/api）后，再转发到 http://localhost:8081
spring:
  cloud:
    gateway:
      routes:
        - id: student-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1

        - id: client-service
          uri: http://localhost:8083
          predicates:
            - Path=/api2/**
          filters:
            - StripPrefix=1