server:
  port: 8081

spring:
  application:
    name: server-demo
  config:
    import: nacos:server-demo?refresh=true # 对应你在Nacos配置中心创建的 Data ID，我开始写成了server-demo.yaml，而nacos里面是server-demo读取配置文件为空

  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        file-extension: yaml          # 配置文件格式
        refresh-enabled: true
      discovery:
        server-addr: localhost:8848

#数据库的的配置放到nacos配置中心
