server:
  port: 8080
spring:
  application:
    name: server-demo
  data:
    redis:
      host: 192.168.1.15
      port: 6379
      database: 0
      connect-timeout: 5000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
